# Generated by Django 4.1.5 on 2023-02-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Borad',
            new_name='Board',
        ),
    ]
